# Generated by Django 4.2.6 on 2023-10-31 08:45

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitmodel_user_alter_habitmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='habit',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habitmodel'),
        ),
    ]
