# Generated by Django 4.2.6 on 2023-10-31 09:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_rename_habit_taskmodel_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='parent',
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='habits.habitmodel'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habits.habitmodel'),
            preserve_default=False,
        ),
    ]
