# Generated by Django 4.2.6 on 2023-10-31 10:00

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_taskmodel_level_remove_taskmodel_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='habit',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habitmodel'),
        ),
    ]
